cat /var/www/html/sysmedicperu/.env
cat /var/www/html/sysmedicperu/public/syscaminar/.env
cat /var/www/html/mt/mastersalud/.env
cat /var/www/html/mt/sistemamadreteresa/.env
cat /var/www/html/mt/huespedes/.env
cat /var/www/html/mt/intimas/.env
cat /var/www/html/mt/victal/.env
cat /var/www/html/sistemamadreteresa/.env
cat /var/www/html/eventos/.env
cat /var/www/html/santaisabel/.env
cat /var/www/html/sedimedic/.env
cat /var/www/html/laboratorios_peru/.env
cat /var/www/html/ganeshas/.env
cat /var/www/html/syspro/.env
cat /var/www/html/syscaminar/.env
cat /var/www/html/reynamadre/.env
cat /var/www/html/madreteresa_productos/.env
cat /var/www/html/lidermedic/.env
cat /var/www/html/multimedic/.env
cat /var/www/html/producto_syspro/.env
cat /var/www/html/ms/mastersalud/.env
cat /var/www/html/wordpress/wp-content/plugins/woocommerce-paypal-payments/vendor/dhii/human-readable-interface/.env
cat /var/www/html/intimas/.env
cat /var/www/html/victal/.env
cat /var/www/html/madreteresa/.env
cat /var/www/html/sysgoldenin/huespedes/.env
cat /var/www/html/ecodiagnostico/.env
cat /var/www/html/sanantoniopadua/.env
cat /var/www/html/sysmadeteresa/.env
cat /var/www/html/grupomastersalud/.env
cat /var/www/html/referencia/syspro/.env
cat /var/www/html/referencia/.env
